CREATE DATABASE demo;

USE demo;

CREATE TABLE Users (
	id INT NOT NULL IDENTITY(1,1) PRIMARY KEY,
	first_name VARCHAR(MAX) NOT NULL,
	last_name VARCHAR(MAX) NOT NULL,
	email VARCHAR(MAX) NOT NULL,
	password VARCHAR(MAX) NOT NULL,
	created_at DATETIME DEFAULT CURRENT_TIMESTAMP,
	updated_at DATETIME DEFAULT CURRENT_TIMESTAMP
);

CREATE TABLE Products (
	id INT NOT NULL IDENTITY(1,1) PRIMARY KEY,
	name VARCHAR(MAX) NOT NULL,
	sku VARCHAR(MAX),
	price FLOAT,
	units_in_stock SMALLINT,
	created_at DATETIME DEFAULT CURRENT_TIMESTAMP,
	updated_at DATETIME DEFAULT CURRENT_TIMESTAMP
);

CREATE TABLE Purchases (
	id INT NOT NULL IDENTITY(1,1) PRIMARY KEY,
	user_id INT FOREIGN KEY REFERENCES Users(id),
	product_id INT FOREIGN KEY REFERENCES Products(id)	
);
