version: '3.8'

services:
  mssql:
    image: mcr.microsoft.com/mssql/server:2022-latest
    container_name: mssql
    hostname: mssql
    environment:
      ACCEPT_EULA: Y
      MSSQL_SA_PASSWORD: adiosplofe12@@
    ports:
      - "1433:1433"
    restart: unless-stopped
    volumes:
      - mssql_data:/var/opt/mssql
    networks:
      - mssql

  minio:
    image: bitnami/minio:latest
    container_name: minio
    ports:
      - 9000:9000
      - 9001:9001
    environment:
      - MINIO_ROOT_USER=minio
      - MINIO_ROOT_PASSWORD=adiosplofe12@@
    volumes:
      - minio:/bitnami/minio/data

  trino:
    image: trinodb/trino:latest
    container_name: trino
    environment:
      - TRINO_ENVIRONMENT=dev
    volumes:
      - ./config/hive.properties:/etc/catalog/hive.properties
    ports:
      - "8080:8080"
    restart: unless-stopped

  hive:
    image: apache/hive:3.1.3
    container_name: hive
    environment:
      - SERVICE_NAME=hiveserver2
    ports:
      - 10000:10000
      - 10002:10002

  metabase:
    image: metabase/metabase
    container_name: metabase
    ports:
      - 3000:3000
    
  demo-script:
    container_name: demo-script
    build: src/
    command: ["tail", "-f", "/dev/null"]
    networks:
      - mssql
    volumes:
      - ./src/insert_data.py:/home/app/insert_data.py

volumes:
  mssql_data:
    driver: local
  minio:
    driver: local

networks:
  mssql:
    driver: bridge
